---
- name: Create all necessary folders
  ansible.builtin.file:
    path: "{{ apache.prefix.config }}/{{ item }}"
    state: directory
    owner: root
    group: "{{ root_group }}"
    mode: 0755
  loop:
    - Includes
    - conf.d

- name: Copy main Apache configuration file
  ansible.builtin.copy:
    src: files/httpd.conf
    dest: "{{ apache.prefix.config }}/httpd.conf"
    mode: "0644"
    owner: root
    group: "{{ root_group }}"

- name: Copy Apache module configuration files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ apache.prefix.config }}/conf.d/{{ item | basename }}"
    mode: "0644"
    owner: root
    group: "{{ root_group }}"
  notify:
    - Test apache config
    - Reload apache
  with_fileglob:
    - "files/conf.d/*.conf"

- name: Template redirect file
  notify:
    - Test apache config
    - Reload apache
  when: apache.redirects is defined
  ansible.builtin.template:
    src: moved_permanently.conf.j2
    dest: "{{ apache.prefix.config }}/Includes/moved_permanently.conf"
    mode: "0644"

- name: Deactivate and stop nginx
  failed_when: no
  ansible.builtin.service:
    name: nginx
    state: stopped
    enabled: false

- name: Start and enable apache
  register: apache_started
  ansible.builtin.service:
    name: "{{ apache.service_name }}"
    state: started
    enabled: true
