- name: Create htpasswd files
  notify:
    - Test apache config
    - Restart apache
  loop: "{{ apache.htpasswd | nginx_flatten_htpasswd }}"
  loop_control:
    label: "{{ htpasswd_file }} username={{ item.username }}"
  vars:
    htpasswd_file: "{{ apache.prefix.config }}/include/{{ item.htpasswd }}.htpasswd"
  community.general.htpasswd:
    path: "{{ htpasswd_file }}"
    group: "{{ apache.user }}"
    mode: "0640"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    crypt_scheme: "{{ item.crypt_scheme }}"
    state: "{{ 'present' if item.password else 'absent' }}"
