- name: Copy logrotate config file for Apache logs
  ansible.builtin.copy:
    src: logrotate.d/apache.conf
    dest: /usr/local/etc/logrotate.d/
    mode: "0644"
    owner: root
    group: "{{ root_group }}"
