---
- name: Restart apache
  when: not apache_started.changed
  ansible.builtin.service:
    name: "{{ apache.service_name }}"
    state: restarted

- name: Reload apache
  when: not apache_started.changed
  ansible.builtin.service:
    name: "{{ apache.service_name }}"
    state: reloaded
