---
- name: Test apache config
  changed_when: no
  ansible.builtin.command:
    cmd: apachectl -t

- name: Restart apache
  when: not apache_started.changed
  ansible.builtin.service:
    name: "{{ apache.service_name }}"
    state: restarted

- name: Reload apache
  when: not apache_started.changed
  ansible.builtin.service:
    name: "{{ apache.service_name }}"
    state: reloaded
