---
- name: Test apache config
  changed_when: no
  ansible.builtin.command:
    cmd: sudo apachectl -t
  register: apachectl

- name: Restart apache
  ansible.builtin.service:
    name: apache24
    state: restarted
  register: restart_apache_result

- name: Reload apache
  ansible.builtin.service:
    name: apache24
    state: reloaded
  when:
    - not (restart_apache_result is defined and restart_apache_result.changed)
    - not apachectl.failed
